StarFormationRate = 2
StarsThatHavePlanets = 1
PlanetsThatSupportLife = 0.3
PlanetsThatDevelopLife = 1
PlanetsThatDevelopIntelligentLife = 0.5
CivlizationsThatReleaseSignals = 0.6
LifetimeOfCivilizations = 0.2
universeDiameterLightSeconds=473040000000
MinStar = 1000
MaxStar = 5000
CivProbability = StarsThatHavePlanets*PlanetsThatSupportLife*PlanetsThatDevelopLife*PlanetsThatDevelopIntelligentLife*CivlizationsThatReleaseSignals*LifetimeOfCivilizations